# Generated by Django 4.2.11 on 2026-02-03 13:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Coupon code (e.g., SUMMER20, FIRST10)', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Internal description of the coupon')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (1-100) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply coupon', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage coupons)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_usage_total', models.PositiveIntegerField(blank=True, help_text='Maximum total uses (null = unlimited)', null=True)),
                ('max_usage_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user', validators=[django.core.validators.MinValueValidator(1)])),
                ('current_usage_count', models.PositiveIntegerField(default=0, help_text='Current total usage count')),
                ('is_user_specific', models.BooleanField(default=False, help_text='Whether coupon is restricted to specific users')),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from this date/time')),
                ('valid_until', models.DateTimeField(help_text='Coupon valid until this date/time')),
                ('is_active', models.BooleanField(default=True, help_text='Whether coupon is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users who can use this coupon (if user-specific)', related_name='exclusive_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(help_text='Order ID where coupon was used')),
                ('order_amount', models.DecimalField(decimal_places=2, help_text='Order amount before discount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount amount applied', max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Order amount after discount', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__830da4_idx'), models.Index(fields=['user', '-used_at'], name='coupons_cou_user_id_b2f20f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_cou_code_3bf721_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_from', 'valid_until'], name='coupons_cou_is_acti_1d54f9_idx'),
        ),
    ]
