# Generated by Django 4.2.11 on 2026-01-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
