# Generated by Django 4.2.11 on 2026-01-16 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this level', validators=[django.core.validators.MinValueValidator(0)])),
                ('auto_disable_on_zero', models.BooleanField(default=True, help_text='Automatically mark product unavailable when stock is 0')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='Product this inventory tracks', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='menu.product')),
            ],
            options={
                'verbose_name': 'Product Inventory',
                'verbose_name_plural': 'Product Inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order', 'Order Placed'), ('cancellation', 'Order Cancelled'), ('restock', 'Manual Restock'), ('adjustment', 'Manual Adjustment'), ('damaged', 'Damaged/Expired')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('quantity_after', models.PositiveIntegerField(help_text='Stock quantity after this transaction')),
                ('order_id', models.IntegerField(blank=True, help_text='Related order ID if applicable', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='menu.productinventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['quantity'], name='menu_produc_quantit_b273a1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['inventory', '-created_at'], name='menu_invent_invento_bf79a8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['transaction_type'], name='menu_invent_transac_c36a38_idx'),
        ),
    ]
