# Generated by Django 4.2.11 on 2026-01-17 16:53

from django.db import migrations, models, connection
from django.utils import timezone


def add_updated_at_if_not_exists(apps, schema_editor):
    """
    Add updated_at column only if it doesn't exist.
    This makes the migration idempotent and safe for Railway deployment.
    """
    with connection.cursor() as cursor:
        # Check if the column exists
        cursor.execute("""
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name='menu_category'
            AND column_name='updated_at';
        """)
        exists = cursor.fetchone()

        if not exists:
            # Column doesn't exist, add it
            cursor.execute("""
                ALTER TABLE menu_category
                ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
            """)


def reverse_migration(apps, schema_editor):
    """Remove the updated_at column if migration is reversed"""
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE menu_category DROP COLUMN IF EXISTS updated_at;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_productinventory_inventorytransaction_and_more'),
    ]

    operations = [
        migrations.RunPython(add_updated_at_if_not_exists, reverse_migration),
    ]
